name: "test"
on:
  push:
    branches: ["main"]
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - name: cd
      uses: actions/checkout@v4
    - name: install .net
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.100'
    - name: build
      run: dotnet build github-actions-test
